@Appointments_HostAddress = http://localhost:5123/api/appointments

GET {{Appointments_HostAddress}}?dentalOfficeId=0199ED58-CD55-79D5-83BC-553367E958C8&startDate=2025-11-01&endDate=2025-12-31
ACCEPT: application/json


###

GET {{Appointments_HostAddress}}/019a24da-124d-7818-9b20-f7bb5b0594d4
ACCEPT: application/json


###

POST {{Appointments_HostAddress}}
Content-Type: application/json

{
  "patientId": "019A0611-08B0-7A5B-97A8-59895027B393",
  "dentistId": "019A1155-F97B-710D-8AC7-73D19B23C849",
  "dentalOfficeId": "0199ED58-CD55-79D5-83BC-553367E958C8",
  "startDate": "2025-12-03T09:30:00",
  "endDate": "2025-12-03T09:45:00"
}

###

POST {{Appointments_HostAddress}}/019A24F4-634F-7C93-8380-000B14A8AE2B/complete

###

POST {{Appointments_HostAddress}}/019A24E6-1CEE-7673-A5C0-44F69451F48B/cancel

###

DELETE {{Appointments_HostAddress}}/019a1019-55f4-712d-ada9-c7ace137e852
Content-Type: application/json

###
