@Appointments_HostAddress = http://localhost:5123/api/appointments

GET {{Appointments_HostAddress}}?dentalOfficeId=0199F3AC-667C-7B64-9C4C-0E0CB9CABF6F&startDate=2025-11-01&endDate=2025-12-31
ACCEPT: application/json


###

GET {{Appointments_HostAddress}}/019A1D22-27EF-79A1-870F-6A92822DC0ED
ACCEPT: application/json


###

POST {{Appointments_HostAddress}}
Content-Type: application/json

{
  "patientId": "019a0cc8-2de2-7962-bfdb-3e57c392fd33",
  "dentistId": "019a2382-5556-7983-9bac-da2e2487cd2c",
  "dentalOfficeId": "0199f3ab-c5ce-7ab7-a4f2-3813f7144cd4",
  "startDate": "2025-12-03T09:30:00",
  "endDate": "2025-12-03T09:45:00"
}

###

PUT {{Appointments_HostAddress}}/019a00e7-d84d-7f5c-bb06-30081320e0a5
Content-Type: application/json

{
  "name": "Felipe Gavilan",
  "email": "felipe@example.com"
}

###

DELETE {{Appointments_HostAddress}}/019a1019-55f4-712d-ada9-c7ace137e852
Content-Type: application/json

###
