<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7933555d-aaee-4785-a0dd-8dd0eb37cf94</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanTeath.Application\CleanTeath.Application.csproj" />
    <ProjectReference Include="..\CleanTeeth.Persistence\CleanTeeth.Persistence.csproj" />
    <ProjectReference Include="..\CleenTeeth.Infrastructure\CleenTeeth.Infrastructure.csproj" />
  </ItemGroup>

</Project>
