@DentalOffices_HostAddress = https://localhost:7096/api/dentalOffices
@Bearer_Token = Bearer CfDJ8Jd2jIUbWb5FgQHXdzbg4q39AtAh0c-b_y7bzI3JgtNIz3TJO-90v5jIh8nxDBo6BktflhbBCUhBBBbq39F3-N9wK4qcNaxbneFMCNs-3kJF64TyQ8vzQxUXyZsCCldRC4drX0JlUwHKXsNh_HFQhLGtCXg3piTMYqqueysktN_YMUXkQO8ELrGNYUZbSUnpq5Zz6609cYITHzKi3G1B6T8-Lpobctn2Yq3Yn5Be0o5qszyKmGbQf_Cntp1ZXEE-Vq2kA9mY_sa7PaeLdK5NjK6LDkR6473hQM-CLuOYBcVGm7vnkoW4909R_SKPI49FGPQHzrvy215Px5cLf0h7rKXcGgKlf2i7x65PlL_-rgd5pLF_WhuClhAmkgZiIUj6-t_tjfqJ6-PQXUxfCHsO-lZAy-RLC60MSNY-uqYf3HA_5p232paXjN9GceANGf6HYCvXnqPojgSI83YSxIE3y-gXGIA9tXuuuTRjksHizdZ9zlEtnHvyJBDibd0srwQqQc-QEbEiUWlsF1soImWUcvh7fxNCfVXsNxtw74WDnDrpf4PIZiICEVHIChcu-nMSXdkMqKKWIJHQs9thTjSGIKRlin81BdspwuLhVidP2sZma-EbapFkNlRfIJELXasLLWkU8UF536ks3s75pqhPT5Itl9wa4SWf7vy-GVMDgckilQN0LkAaflJhgtmJsk8V2MVEqt3P0sulK602E7bkBybAQq_ibaxvpmro2KXh7V8n

GET {{DentalOffices_HostAddress}}
ACCEPT: application/json
Authorization: {{Bearer_Token}}


###

GET {{DentalOffices_HostAddress}}/0199ed58-cd55-79d5-83bc-553367e958c8
ACCEPT: application/json
Authorization: {{Bearer_Token}}


###

POST {{DentalOffices_HostAddress}}
Authorization: {{Bearer_Token}}
Content-Type: application/json

{
  "name": "Dental Office D"
}

###

PUT {{DentalOffices_HostAddress}}/019a3420-21f4-7bec-b7eb-a15d1362f06f
Authorization: {{Bearer_Token}}
Content-Type: application/json

{
  "name": "Dental Office D - Updated"
}

###

DELETE {{DentalOffices_HostAddress}}/0199fb14-64c7-7cad-8262-b9e88c12b909

###
