@DentalOffices_HostAddress = https://localhost:7096/api/dentalOffices
@Bearer_Token = Bearer CfDJ8Jd2jIUbWb5FgQHXdzbg4q1MaAIM6clEO7-r0_HHoIZ4QRH3_QO2-mRMIWFv4JdaOC5HaHMXrH6YBpXdfKq3y3HtwZhyslsXMBNqjUQZSpSaIdyDiDNCGbRoQyauzIx37pwpwB9W5RECYz5XMTVJK16dzRdGe9rIPsuvgqDkMJzsI6XwQ134h4IMrDcFNd6qgxA7lVtUixnmdiyqkhDDu_uZ2hkAxfWyvlgq6kbkUOg2FL3KuJf4iBB7RG_vwdcnP6OYRnYmdA0tpo3VtXKSEZIhB8vPeDbCNC_5blBrtHfSQOXI5yO7GOs0WqczfKaE4BOjrOkkVgKgja7v6_wAuwUsKXR-NLIT4KchbKSmVJ4AeOf4OZ3yOSUt5zWXch9WfBbQn2mXbaA_xC7eb1AslxThlkG1t-8RUtd6E8sZ337YJWpgKslwuf0H6LpNedky_poknQmOCqc-gHeIpBG8ZEg3nW7SB3r512XOzJQUBXg3k_Ry4ryFHJdajOXEptHpdOTuH0x8G7WCpE-0WiN4wAfm_rWrLgZuZsQtZ_5BxdQBacZ7QkmbxN8AKG1pkR3pn_3b0wkZnTtH6V6z67Xt22aIq4Zf4rGg0lIijxGaIQPXtNGlDJl92WC2NziBG2yozNQuEAB_P2xfg2WAB-clk5P9eqy3H3FfibWIej7GYmi7NNGmVhd2xIvhqBHY2oMypyZpEEgOCDCb6ZdK_HSdRZWq-ZsDRf7XeG5LTvAFxSXa

GET {{DentalOffices_HostAddress}}
ACCEPT: application/json
Authorization: {{Bearer_Token}}


###

GET {{DentalOffices_HostAddress}}/0199ed58-cd55-79d5-83bc-553367e958c8
ACCEPT: application/json
Authorization: {{Bearer_Token}}


###

POST {{DentalOffices_HostAddress}}
Content-Type: application/json

{
  "name": "Dental Office C"
}

###

PUT {{DentalOffices_HostAddress}}/0199f3ab-c5ce-7ab7-a4f2-3813f7144cd4
Content-Type: application/json

{
  "name": "Dental Office A - Updated"
}

###

DELETE {{DentalOffices_HostAddress}}/0199fb14-64c7-7cad-8262-b9e88c12b909

###
