@Dentists_HostAddress = https://localhost:7096/api/dentists
@Bearer_Token = Bearer CfDJ8KRGsvTdQUdEpv01wn3xeMTBmdDKUY43o1nPrFGfhTKxmX_gF0UH94kfMfqULZl5uUG0zDVXj16DHHJVTViQPu3s4w9IBlfpGaKz5cVS31wOisxVk3le7VTyHqXwk0VdhV16tzvPv-2nzJxz0h6sAI1RX258qddBd3YavKICZgVPFWyAJcNpRDE1zSwv6CvKXPblNvpufFS6sX06FYk_VacoCucM2tFNA1MIuSEgZKzPVJn1_2EdnIdb662SfYDtj0Rwi2hndrEmS6aYuQ143LAmf5t7WnzH5-AKhcwF8BEO9BdTAnOrwp9riV7HlY1uz1datn0kMwqSwc9D6R74TnexNXEbonhlnG0W8xC2uNHXbeh9jWg1pD5-hV66l6sJz0mFpF6QnY8NuNpaY9jofhcrfiua6V20kcPBSOTihEplpyywKE4nXgcMJhIFwvdqEW2WwePdRHPWdNHlOmPm1p3kM7BEOUcMndTPivqZOm8HxtBoblIki_C1VZB86s_nAnyogqwcLZmKIc-SKLFA4iJvdm1Gtq7uMa1io1wYu3rUpuMRtoQO7IYxEvWhWgCCHYxd3veyIz3BloCZGrxSBgCcfH0122O2-hOez2yOylrU3DvntkurOi7xlpJFu-KSYztHSkZJqPOYqvcfIUeixTuB-Vp4dONOhpJeVehxGM-7WDvVLyywh3_RTw8sTwshbN9iCE2pCO7_iOelUruHxJ0

GET {{Dentists_HostAddress}}?page=1&recordsPerPage=10
ACCEPT: application/json


###

GET {{Dentists_HostAddress}}/019a1156-c850-7601-8669-bdde02d23e82
ACCEPT: application/json


###

POST {{Dentists_HostAddress}}
Content-Type: application/json

{
  "name": "Dentist A",
  "email": "dentist@example.com"
}

###

PUT {{Dentists_HostAddress}}/019a2382-5556-7983-9bac-da2e2487cd2c
Content-Type: application/json

{
  "name": "Robert Simmons",
  "email": "simmons@example.com"
}

###

DELETE {{Dentists_HostAddress}}/019a1156-c850-7601-8669-bdde02d23e82
Content-Type: application/json

###
