@Patients_HostAddress = http://localhost:5123/api/patients

GET {{Patients_HostAddress}}?page=1&recordsPerPage=10
ACCEPT: application/json


###

GET {{Patients_HostAddress}}/019a0cc9-5ad2-7834-951e-12deb189a75a
ACCEPT: application/json


###

POST {{Patients_HostAddress}}
Content-Type: application/json

{
  "name": "Patient to be deleted",
  "email": "deleted@example.com"
}

###

PUT {{Patients_HostAddress}}/019a0cc8-7dfb-7a01-aeed-17608530d817
Content-Type: application/json

{
  "name": "Felipe Gavilan",
  "email": "makhirmjd@gmail.com"
}

###

DELETE {{Patients_HostAddress}}/019a1019-55f4-712d-ada9-c7ace137e852
Content-Type: application/json

###
